services:
  ecu_dashboard:
    profiles:
      - car
    image: ghcr.io/distributed-systems-experimentation/ecu_dashboard/ecu_dashboard:v0.1.1
    build:
      context: ./ecu_dashboard
      dockerfile: Dockerfile
      network: host
    container_name: ecu_dashboard
    develop:
      watch:
        - action: rebuild
          path: ./ecu_dashboard
